name: Static Application Security Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: read

jobs:
  run_sobelow_scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: run-action
        uses: sobelow/action@v1
        with:
          report: false
          flags: --format json